# Generated by Django 4.2 on 2023-08-12 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ResumeData",
            fields=[
                ("ID", models.AutoField(primary_key=True, serialize=False)),
                ("Name", models.CharField(max_length=100)),
                ("Email_ID", models.CharField(max_length=50)),
                ("resume_score", models.CharField(max_length=8)),
                ("Timestamp", models.CharField(max_length=50)),
                ("Page_no", models.CharField(max_length=5)),
                ("Predicted_Field", models.CharField(max_length=25)),
                ("User_level", models.CharField(max_length=30)),
                ("Actual_skills", models.CharField(max_length=300)),
                ("Recommended_skills", models.CharField(max_length=300)),
                ("Recommended_courses", models.CharField(max_length=300)),
            ],
        ),
    ]
