# Generated by Django 4.2 on 2023-08-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidate", "0002_resumedata_recruiter_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resumedata",
            name="Actual_skills",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="resumedata",
            name="Predicted_Field",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="resumedata",
            name="Recommended_courses",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="resumedata",
            name="Recommended_skills",
            field=models.CharField(max_length=1000),
        ),
    ]
