# Generated by Django 4.2 on 2023-08-12 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recruiter", "0002_registereduser_delete_user"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="registereduser",
            managers=[],
        ),
    ]
